/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/documents': RouteRecordInfo<
      '/documents',
      '/documents',
      Record<never, never>,
      Record<never, never>,
      | 'document'
      | 'documents'
    >,
    'documents': RouteRecordInfo<
      'documents',
      '/documents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'document': RouteRecordInfo<
      'document',
      '/documents/:documentId',
      { documentId: ParamValue<true> },
      { documentId: ParamValue<false> },
      | never
    >,
    'home': RouteRecordInfo<
      'home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'register': RouteRecordInfo<
      'register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scanners': RouteRecordInfo<
      '/scanners',
      '/scanners',
      Record<never, never>,
      Record<never, never>,
      | 'scanner'
      | 'scanners'
    >,
    'scanners': RouteRecordInfo<
      'scanners',
      '/scanners',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'scanner': RouteRecordInfo<
      'scanner',
      '/scanners/:scannerId',
      { scannerId: ParamValue<true> },
      { scannerId: ParamValue<false> },
      | never
    >,
    'settings': RouteRecordInfo<
      'settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/documents.vue': {
      routes:
        | '/documents'
        | 'document'
        | 'documents'
      views:
        | 'default'
    }
    'src/pages/documents/index.vue': {
      routes:
        | 'documents'
      views:
        | never
    }
    'src/pages/documents/[documentId].vue': {
      routes:
        | 'document'
      views:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | 'home'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | 'register'
      views:
        | never
    }
    'src/pages/scanners.vue': {
      routes:
        | '/scanners'
        | 'scanner'
        | 'scanners'
      views:
        | 'default'
    }
    'src/pages/scanners/index.vue': {
      routes:
        | 'scanners'
      views:
        | never
    }
    'src/pages/scanners/[scannerId].vue': {
      routes:
        | 'scanner'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | 'settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
